### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by ahmedreyad2019** [zju3dv/clean-pvnet#101]
i am trying to use pytorch 0.4.1 because 1.1.0 was very slow but I get that error:
Traceback (most recent call last):
  File "train_net.py", line 57, in <module>
    main()
  File "train_net.py", line 49, in main
    network = make_network(cfg)
  File "/content/drive/My Drive/clean-pvnet-master/lib/networks/make_network.py", line 34, in make_network
    return imp.load_source(module, path).get_network(cfg)
  File "/usr/local/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "lib/networks/pvnet/__init__.py", line 1, in <module>
    from .resnet18  import get_res_pvnet
  File "lib/networks/pvnet/resnet18.py", line 5, in <module>
    from lib.csrc.ransac_voting.ransac_voting_gpu import ransac_voting_layer, ransac_voting_layer_v3, estimate_voting_distribution_with_mean
  File "/content/drive/My Drive/clean-pvnet-master/lib/csrc/ransac_voting/ransac_voting_gpu.py", line 2, in <module>
    import lib.csrc.ransac_voting.ransac_voting as ransac_voting
ImportError: /content/drive/My Drive/clean-pvnet-master/lib/csrc/ransac_voting/ransac_voting.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E

**Comment by pengsida** [comment]
If you change the pytorch version, you need to re-compile the code.
The pytorch 1.1.0 is very slow with dilated convolution.

**Comment by ahmedreyad2019** [comment]
> need to re-co

what do you mean by recompile the code?
I restarted everythin from the beginning again and the same problem occurs.

Any suggestions?

**Comment by pengsida** [comment]
```
ROOT=/path/to/clean-pvnet
cd $ROOT/lib/csrc/ransac_voting
python setup.py build_ext --inplace
```

**Comment by ahmedreyad2019** [comment]
> ```
> ROOT=/path/to/clean-pvnet
> cd $ROOT/lib/csrc/ransac_voting
> python setup.py build_ext --inplace
> ```

still not working. deleted everything and started from scratch and I have the same problem. when i return to pytorch 1.1.0 it works normally,

**Comment by pengsida** [comment]
Maybe the pytorch version does not match to the cuda version.
