### ISSUE TITLE
Image Size

### ISSUE THREAD

**Issue by mandywoo** [zju3dv/clean-pvnet#102]
Does the training only work with square images? I tried images of size 310x672 and got this error. But when I change the image size to 448x448, it works perfectly.

Traceback (most recent call last):
  File "train_net.py", line 63, in <module>
    main()
  File "train_net.py", line 59, in main
    train(cfg, network)
  File "train_net.py", line 37, in train
    trainer.val(epoch, val_loader, evaluator, recorder)
  File "/home/ubuntu/clean-pvnet/lib/train/trainers/trainer.py", line 82, in val
    output, loss, loss_stats, image_stats = self.network.module(batch)
  File "/home/ubuntu/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/train/trainers/pvnet.py", line 16, in forward
    output = self.net(batch['inp'])
  File "/home/ubuntu/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/pvnet/resnet18.py", line 89, in forward
    fm=self.conv2s(torch.cat([fm,x2s],1))
RuntimeError: Sizes of tensors must match except in dimension 3. Got 155 and 156.

**Comment by pengsida** [comment]
The image size should be a multiple of 32.

**Comment by pureYioYi** [comment]
大佬，输入图像的尺寸现在是不是不只需要是32倍数？

这是我在 `lib/datasets/samplers.py`下面找到的代码，将输入的图像进行随机resize，其中`size_int = 8`
  def generate_height_width(self):
      hi, wi = np.random.randint(0, self.hint), np.random.randint(0, self.wint)
      h, w = self.hmin + hi * self.size_int, self.wmin + wi * self.size_int
      return h, w

然后resize后的图像大小为：256+8*n

**Comment by pengsida** [comment]
你输入的图像是做什么用的？测试还是训练？

**Comment by pengsida** [comment]
我不记得了，你可以试试。
