### ISSUE TITLE
uncertain ty_pnp_command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by zhuyazhi** [zju3dv/clean-pvnet#106]
您好，我想请问一下这个问题怎么解决？我已经看了issue中一些类似的问，但是没有找到解决办法，谢谢您
root@terminal16ea5f3f:/opt/data/private/zhuyazhi/clean-pvnet-master_uncertainty-pnp/lib/csrc/uncertain
ty_pnp# python3 setup.py build_ext --inplace
generating ./_ext.c
(already up-to-date)
the current directory is '/opt/data/private/zhuyazhi/clean-pvnet-master_uncertainty-pnp/lib/csrc/uncertainty_pnp'
running build_ext
building '_ext' extension
gcc -pthread -B /root/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/include/python3.6m -c _ext.c -o ./_ext.o
gcc -pthread -shared -B /root/anaconda3/compiler_compat -L/root/anaconda3/lib -Wl,-rpath=/root/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_ext.o src/uncertainty_pnp.cpp.o ./lib/libceres.so ./lib/libglog.so -lstdc++ -o ./_ext.cpython-36m-x86_64-linux-gnu.so
/root/anaconda3/compiler_compat/ld:./lib/libceres.so: file format not recognized; treating as linker script
/root/anaconda3/compiler_compat/ld:./lib/libceres.so:0: syntax error
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/root/anaconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/root/anaconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/root/anaconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/root/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/root/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/root/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/root/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/root/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/root/anaconda3/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/root/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    ffibuilder.compile(verbose=True)
  File "/root/anaconda3/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/root/anaconda3/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/root/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/root/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

**Comment by zhuyazhi** [comment]
[76](https://github.com/zju3dv/clean-pvnet/issues/76)
