### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by Sai-krishna-reddy** [zju3dv/clean-pvnet#107]
(pvnet) saikrishna@saikrishna-HP-Pavilion-Laptop-15-ck0xx:~/clean-pvnet$ python run.py --type evaluate --cfg_file configs/linemod.yaml model cat cls_type cat
loading annotations into memory...
Done (t=0.07s)
creating index...
index created!
Traceback (most recent call last):
  File "run.py", line 226, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 74, in run_evaluate
    evaluator = make_evaluator(cfg)
  File "/home/saikrishna/clean-pvnet/lib/evaluators/make_evaluator.py", line 19, in make_evaluator
    return _evaluator_factory(cfg)
  File "/home/saikrishna/clean-pvnet/lib/evaluators/make_evaluator.py", line 11, in _evaluator_factory
    evaluator = imp.load_source(module, path).Evaluator(cfg.result_dir)
  File "/home/saikrishna/anaconda3/envs/pvnet/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "lib/evaluators/linemod/pvnet.py", line 20, in <module>
    from lib.csrc.nn import nn_utils
  File "/home/saikrishna/clean-pvnet/lib/csrc/nn/nn_utils.py", line 1, in <module>
    from lib.csrc.nn._ext import lib, ffi
ModuleNotFoundError: No module named 'lib.csrc.nn._ext'

how to resolve this error ?

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/85977746-c58f4c80-ba0f-11ea-8f61-52db36a59cc0.png)
