### ISSUE TITLE
No src/uncertainty_pnp.cpp.o on CentOS 7 

### ISSUE THREAD

**Issue by cheolho** [zju3dv/clean-pvnet#113]
While compiling uncertainty_pnp,
I met the error `No src/uncertainty_pnp.cpp.o`

I installed the following packages (CentOS 7):
`sudo yum install glog.x86_64 glog-devel.x86_64 glogg suitesparse-devel atlas-devel`

How can I compile uncertainty_pnp?

**Comment by pengsida** [comment]
Please provide the detailed error message.

**Comment by cheolho** [comment]
the error message is shown as follows:
```
$ python setup.py build_ext                                                                                                                                                              --inplace
In file included from ./include/ceres/internal/fixed_array.h:38:0,
                 from ./include/ceres/internal/autodiff.h:147,
                 from ./include/ceres/autodiff_cost_function.h:133,
                 from ./include/ceres/ceres.h:37,
                 from src/uncertainty_pnp.cpp:3:
/usr/include/glog/logging.h:85:27: fatal error: gflags/gflags.h: No such file or                                                                                                                                                              directory
 #include <gflags/gflags.h>
                           ^
compilation terminated.
generating ./_ext.c
(already up-to-date)
the current directory is 'clean-pvnet/lib                                                                                                                                                             /csrc/uncertainty_pnp'
running build_ext
building '_ext' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-                                                                                                                                                             D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size                                                                                                                                                             =4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -                                                                                                                                                             I/Envs/py36/include -I/usr/include/python3.6m -c _ext.c                                                                                                                                                              -o ./_ext.o
gcc -pthread -shared -Wl,-z,relro -g ./_ext.o src/uncertainty_pnp.cpp.o ./lib/li                                                                                                                                                             bceres.so ./lib/libglog.so -L/usr/lib64 -lstdc++ -lpython3.6m -o ./_ext.cpython-                                                                                                                                                             36m-x86_64-linux-gnu.so
gcc: error: src/uncertainty_pnp.cpp.o: No such file or directory
Traceback (most recent call last):
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 205, in link
    self.spawn(linker + ld_args)
  File "/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Envs/py36/lib64/python3.6/site-packages/cffi/f                                                                                                                                                             fiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build                                                                                                                                                             _extensions
    self._build_extensions_serial()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _buil                                                                                                                                                             d_extensions_serial
    self.build_extension(ext)
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 558, in build                                                                                                                                                             _extension
    target_lang=language)
  File "/usr/lib64/python3.6/distutils/ccompiler.py", line 717, in link_shared_o                                                                                                                                                             bject
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 207, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    ffibuilder.compile(verbose=True)
  File "/Envs/py36/lib64/python3.6/site-packages/cffi/a                                                                                                                                                             pi.py", line 727, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/Envs/py36/lib64/python3.6/site-packages/cffi/r                                                                                                                                                             ecompiler.py", line 1536, in recompile
    compiler_verbose, debug)
  File "/Envs/py36/lib64/python3.6/site-packages/cffi/f                                                                                                                                                             fiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/Envs/py36/lib64/python3.6/site-packages/cffi/f                                                                                                                                                             fiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'gcc' failed with exit status 1
```

**Comment by pengsida** [comment]
The problem is caused by `fatal error: gflags/gflags.h: No such file or directory #include <gflags/gflags.h>`.
Maybe you could consult this: https://bugzilla.redhat.com/show_bug.cgi?id=1300053

**Comment by cheolho** [comment]
It worked by installing gflags by `yum install gflags-devel`. Thanks a lot.

**Comment by ghoshaw** [comment]
@cheolho , Hi, how you install libglfw3 in centos7, I can not yum install it, and make it from source code need a lot other libs.

**Comment by cheolho** [comment]
> @cheolho , Hi, how you install libglfw3 in centos7, I can not yum install it, and make it from source code need a lot other libs.

I do not have a complete list of dependencies. However, I installed the following:
```
sudo rpm -ivh https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/g/glfw-3.2.1-2.el7.x86_64.rpm
sudo rpm -ivh  https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/g/glfw-devel-3.2.1-2.el7.x86_64.rpm
pip install cyglfw3
```
