### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.csrc.nn._ext'

### ISSUE THREAD

**Issue by sandy-ssdut** [zju3dv/clean-pvnet#126]
Hi,

When I tried to test linemod by the pretrained mode, I got this error. 

>>> python run.py --type evaluate --cfg_file configs/linemod.yaml model cat cls_type cat

Load model: data/model/pvnet/cat/199.pth
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
Traceback (most recent call last):
  File "run.py", line 226, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 74, in run_evaluate
    evaluator = make_evaluator(cfg)
  File "/home/liuzhaoliang/WorkSpace/3DTracking/pose_estimation/clean-pvnet/lib/evaluators/make_evaluator.py", line 19, in make_evaluator
    return _evaluator_factory(cfg)
  File "/home/liuzhaoliang/WorkSpace/3DTracking/pose_estimation/clean-pvnet/lib/evaluators/make_evaluator.py", line 11, in _evaluator_factory
    evaluator = imp.load_source(module, path).Evaluator(cfg.result_dir)
  File "/home/liuzhaoliang/WorkSpace/program/anaconda/anaconda/envs/pvnet/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "lib/evaluators/linemod/pvnet.py", line 20, in <module>
    from lib.csrc.nn import nn_utils
  File "/home/liuzhaoliang/WorkSpace/3DTracking/pose_estimation/clean-pvnet/lib/csrc/nn/nn_utils.py", line 1, in <module>
    from lib.csrc.nn._ext import lib, ffi
ModuleNotFoundError: No module named 'lib.csrc.nn._ext'

How can I fix it?

**Comment by sandy-ssdut** [comment]
I fix this error by rebuild nn. 

Thanks!

**Comment by AmokraneIlhem** [comment]
Hi @sandy-ssdut , 
Please, how exactly did you solve this problem? 
thank u in advance.
