### ISSUE TITLE
用cuda10编译报错

### ISSUE THREAD

**Issue by zsnyjj1993** [zju3dv/clean-pvnet#155]
cuda10, 在执行
cd ../nn
python setup.py build_ext --inplace

报错信息：
In file included from /usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h:217:0:
/usr/local/cuda/include/crt/host_runtime.h:19:2: warning: #warning "crt/device_functions.h is an internal header file and must not be used directly.  Please use cuda_runtime_api.h or cuda_runtime.h instead." [-Wcpp]
 #warning "crt/device_functions.h is an internal header file and must not be used directly.  Please use cuda_runtime_api.h or cuda_runtime.h instead."
  ^~~~~~~
In file included from /tmp/tmpxft_00002006_00000000-5_nearest_neighborhood.cudafe1.stub.c:5:0,
                 from tmpxft_00002006_00000000-5_nearest_neighborhood.cudafe1.stub.c:1:
/usr/local/cuda/include/crt/host_runtime.h:19:2: warning: #warning "crt/device_functions.h is an internal header file and must not be used directly.  Please use cuda_runtime_api.h or cuda_runtime.h instead." [-Wcpp]
 #warning "crt/device_functions.h is an internal header file and must not be used directly.  Please use cuda_runtime_api.h or cuda_runtime.h instead."
  ^~~~~~~
/tmp/tmpxft_00002006_00000000-5_nearest_neighborhood.cudafe1.stub.c: In function ‘void __device_stub__Z27findNearestPoint3DIdxKernelPfS_Piiiii(float*, float*, int*, int, int, int, int)’:
/tmp/tmpxft_00002006_00000000-5_nearest_neighborhood.cudafe1.stub.c:11:153: error: ‘__args_arr’ was not declared in this scope
 arestPoint3DIdxKernelPfS_Piiiii(float *__par0, float *__par1, int *__par2, int __par3, int __par4, int __par5, int __par6){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaSetupArgSimple(__par3, 24UL);__cudaSetupArgSimple(__par4, 28UL);__cudaSetupArgSimple(__par5, 32UL);__cudaSetupArgSimple(__par6, 36UL);__cudaLaunch(((char *)((void ( *)(float *, float *, int *, int, int, int, int))findNearestPoint3DIdxKernel)));}
                                                                                                                            ^
/tmp/tmpxft_00002006_00000000-5_nearest_neighborhood.cudafe1.stub.c:11:153: error: ‘__args_idx’ was not declared in this scope
 arestPoint3DIdxKernelPfS_Piiiii(float *__par0, float *__par1, int *__par2, int __par3, int __par4, int __par5, int __par6){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaSetupArgSimple(__par3, 24UL);__cudaSetupArgSimple(__par4, 28UL);__cudaSetupArgSimple(__par5, 32UL);__cudaSetupArgSimple(__par6, 36UL);__cudaLaunch(((char *)((void ( *)(float *, float *, int *, int, int, int, int))findNearestPoint3DIdxKernel)));}
                                                                                                                            ^
/tmp/tmpxft_00002006_00000000-5_nearest_neighborhood.cudafe1.stub.c: In function ‘void __device_stub__Z27findNearestPoint2DIdxKernelPfS_Piiiii(float*, float*, int*, int, int, int, int)’:
/tmp/tmpxft_00002006_00000000-5_nearest_neighborhood.cudafe1.stub.c:2:35: error: ‘__args_arr’ was not declared in this scope
 #pragma GCC diagnostic ignored "-Wunused-function"
                                   ^
/tmp/tmpxft_00002006_00000000-5_nearest_neighborhood.cudafe1.stub.c:2:35: error: ‘__args_idx’ was not declared in this scope
 #pragma GCC diagnostic ignored "-Wunused-function"
                                   ^
generating ./_ext.c
(already up-to-date)
the current directory is '/home/shengnan/research/clean-pvnet/lib/csrc/nn'
running build_ext
building '_ext' extension
gcc -pthread -B /home/shengnan/anaconda3/envs/pvnet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/shengnan/anaconda3/envs/pvnet/include/python3.7m -c _ext.c -o ./_ext.o
gcc -pthread -shared -B /home/shengnan/anaconda3/envs/pvnet/compiler_compat -L/home/shengnan/anaconda3/envs/pvnet/lib -Wl,-rpath=/home/shengnan/anaconda3/envs/pvnet/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_ext.o src/nearest_neighborhood.cu.o /usr/local/cuda/lib64/libcudart.so -lstdc++ -o ./_ext.cpython-37m-x86_64-linux-gnu.so
gcc: error: src/nearest_neighborhood.cu.o: No such file or directory
Traceback (most recent call last):
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/distutils/unixccompiler.py", line 205, in link
    self.spawn(linker + ld_args)
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

这个错误怎么解决啊，我看您在别的issue中写道用cuda10编译成功了，需要修该什么吗

**Comment by pengsida** [comment]
你gcc什么版本的

**Comment by zsnyjj1993** [comment]
谢谢回复，gcc是7.5.0
我找到一个可能的错误是，cuda(10.0)和nvcc(9.0)版本不匹配，然后我把nvcc改成10.0了，又出现了新的错误
nvcc fatal   : Path to libdevice library not specified
generating ./_ext.c
(already up-to-date)
the current directory is '/home/shengnan/research/clean-pvnet/lib/csrc/nn'
running build_ext
building '_ext' extension
gcc -pthread -B /home/shengnan/anaconda3/envs/pvnet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/shengnan/anaconda3/envs/pvnet/include/python3.7m -c _ext.c -o ./_ext.o
gcc -pthread -shared -B /home/shengnan/anaconda3/envs/pvnet/compiler_compat -L/home/shengnan/anaconda3/envs/pvnet/lib -Wl,-rpath=/home/shengnan/anaconda3/envs/pvnet/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_ext.o src/nearest_neighborhood.cu.o /usr/local/cuda-10.0/lib64/libcudart.so -lstdc++ -o ./_ext.cpython-37m-x86_64-linux-gnu.so
gcc: error: src/nearest_neighborhood.cu.o: No such file or directory
Traceback (most recent call last):
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/distutils/unixccompiler.py", line 205, in link
    self.spawn(linker + ld_args)
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/distutils/command/build_ext.py", line 559, in build_extension
    target_lang=language)
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/distutils/unixccompiler.py", line 207, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    ffibuilder.compile(verbose=True)
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/api.py", line 727, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/recompiler.py", line 1555, in recompile
    compiler_verbose, debug)
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/shengnan/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'gcc' failed with exit status 1

nvcc fatal   : Path to libdevice library not specified，新出现了这个错误，悲催...

**Comment by pengsida** [comment]
如果你用的是cuda 10，nvcc就应该是10的，不存在会出现9.0的问题。可能是你环境没设置对。

**Comment by zsnyjj1993** [comment]
重装cuda后问题解决了，谢谢
