### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by emilychen6160** [zju3dv/clean-pvnet#156]
您好，請問我們如果想要用自定義數據進行訓練，出現以下問題，可能的原因大概為何？
Traceback (most recent call last):
  File "run.py", line 226, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 222, in run_custom
    handle_custom_dataset.custom_to_coco(data_root)
  File "/media/NDDS/clean-pvnet-master/tools/handle_custom_dataset.py", line 110, in custom_to_coco
    img_id, ann_id = record_ann(model_meta, img_id, ann_id, images, annotations)
  File "/media/NDDS/clean-pvnet-master/tools/handle_custom_dataset.py", line 67, in record_ann
    corner_2d = base_utils.project(corner_3d, K, pose)
  File "/media/NDDS/clean-pvnet-master/lib/utils/base_utils.py", line 23, in project
    xyz = np.dot(xyz, RT[:, :3].T) + RT[:, 3:].T
ValueError: operands could not be broadcast together with shapes (8,3,480) (3,637,480) 
當前的ply檔是用blender產生的，但是每個頂點少了您範例中3個rgb參數，請問輸入的練資料（相片、模型檔）是否有什麼規矩？謝謝您

**Comment by pengsida** [comment]
RT可能设置的有问题。
建议你看看我提供的例子的数据格式。

**Comment by emilychen6160** [comment]
謝謝，所以看起來似乎是pose資料夾下的數據設置有錯嗎？我是將rgb資料夾下的.jpg以檔案轉檔的方式生成，不知道這樣的方式是算合理嗎？

**Comment by pengsida** [comment]
不合理。
你了解6d object pose吗？它是一个3 x 4的矩阵。

**Comment by emilychen6160** [comment]
所以以您提供的數據格式，"pose"這個資料夾應當擺放分別每張照片所分別有的3x4旋轉&平移數據矩陣，並壓縮成.npy格式嗎？

**Comment by pengsida** [comment]
对的。
