### ISSUE TITLE
  File "lib/evaluators/linemod/pvnet.py", line 19, in <module>     from transforms3d.quaternions import mat2quat, quat2mat ModuleNotFoundError: No module named 'transforms3d'

### ISSUE THREAD

**Issue by WL9395** [zju3dv/clean-pvnet#161]
Dear author,
Can you help me solve this problem? 

when I try:  python run.py --type evaluate --cfg_file configs/linemod.yaml model cat cls_type cat

The error information is as follows:

Load model: data/model/pvnet/cat/199.pth
loading annotations into memory...
Done (t=0.08s)
creating index...
index created!
Traceback (most recent call last):
  File "run.py", line 248, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 74, in run_evaluate
    evaluator = make_evaluator(cfg)
  File "/media/wl/work/clean-pvnet/lib/evaluators/make_evaluator.py", line 19, in make_evaluator
    return _evaluator_factory(cfg)
  File "/media/wl/work/clean-pvnet/lib/evaluators/make_evaluator.py", line 11, in _evaluator_factory
    evaluator = imp.load_source(module, path).Evaluator(cfg.result_dir)
  File "/media/wl/work/anaconda3/envs/pvnet/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "lib/evaluators/linemod/pvnet.py", line 19, in <module>
    from transforms3d.quaternions import mat2quat, quat2mat
ModuleNotFoundError: No module named 'transforms3d'

**Comment by pengsida** [comment]
pip install transforms3d
