### ISSUE TITLE
Testing on Linemod Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by WL9395** [zju3dv/clean-pvnet#163]
Dear author,
Can you help me solve this problem?

when I try:    python run.py --type evaluate --cfg_file configs/linemod.yaml model cat cls_type cat

The error information is as follows:

Load model: data/model/pvnet/cat/199.pth
loading annotations into memory...
Done (t=0.07s)
creating index...
index created!
loading annotations into memory...
Done (t=0.05s)
creating index...
index created!
  0%|                                                  | 0/1002 [00:00<?, ?it/s]
Segmentation fault (core dumped)

**Comment by WL9395** [comment]
my computer is cuda-9.0 ubuntu16.04

**Comment by pengsida** [comment]
Could you find where the code failed?
Which line?

**Comment by WL9395** [comment]
sorry, I couldn't find it.
my torch version is v1.1， I'm not sure if it has an impact on the process.

**Comment by pengsida** [comment]
Maybe.

**Comment by WL9395** [comment]
I tried to install pytorch V0.4.1, the original problem disappeared, but a new problem appeared：


python run.py --type evaluate --cfg_file configs/linemod.yaml model cat cls_type cat

Traceback (most recent call last):
  File "run.py", line 248, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 69, in run_evaluate
    network = make_network(cfg).cuda()
  File "/media/wl/work/clean-pvnet/lib/networks/make_network.py", line 34, in make_network
    return imp.load_source(module, path).get_network(cfg)
  File "/media/wl/work/anaconda3/envs/cleanpvnet/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "lib/networks/pvnet/__init__.py", line 1, in <module>
    from .resnet18  import get_res_pvnet
  File "lib/networks/pvnet/resnet18.py", line 5, in <module>
    from lib.csrc.ransac_voting.ransac_voting_gpu import ransac_voting_layer, ransac_voting_layer_v3, estimate_voting_distribution_with_mean
  File "/media/wl/work/clean-pvnet/lib/csrc/ransac_voting/ransac_voting_gpu.py", line 2, in <module>
    import lib.csrc.ransac_voting.ransac_voting as ransac_voting
ImportError: /media/wl/work/clean-pvnet/lib/csrc/ransac_voting/ransac_voting.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E

**Comment by pengsida** [comment]
Delete the build directory under ransac_voting and re-compile the code.

**Comment by HannahHaensen** [comment]
@WL9395 have you tried it on a newer version of pytorch?

I fail with:
```
UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at  ../aten/src/ATen/native/IndexingUtils.h:28.)
  direct = vertex[bi].masked_select(torch.unsqueeze(torch.unsqueeze(cur_mask, 2), 3))  # [tn,vn,2]
Segmentation fault (core dumped)
```
