### ISSUE TITLE
numpy.ndarray has the wrong size, try recompiling. Expected 80, got 88

### ISSUE THREAD

**Issue by luigifaticoso** [zju3dv/clean-pvnet#167]
Hello, 
I am trying to train a custom dataset and I'm starting to work on the custom dataset available for download in the readme. 
By following the guide and using the dockerfile to install the tools, when running the train command this is the output:
```shell
python train_net.py --cfg_file configs/custom.yaml train.batch_size 4
Traceback (most recent call last):
  File "train_net.py", line 57, in <module>
    main()
  File "train_net.py", line 53, in main
    train(cfg, network)
  File "train_net.py", line 17, in train
    evaluator = make_evaluator(cfg)
  File "/home/robotronics/pvnet/lib/evaluators/make_evaluator.py", line 19, in make_evaluator
    return _evaluator_factory(cfg)
  File "/home/robotronics/pvnet/lib/evaluators/make_evaluator.py", line 11, in _evaluator_factory
    evaluator = imp.load_source(module, path).Evaluator(cfg.result_dir)
  File "/opt/conda/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "lib/evaluators/custom/pvnet.py", line 3, in <module>
    import pycocotools.coco as coco
  File "/opt/conda/lib/python3.7/site-packages/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/opt/conda/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "__init__.pxd", line 199, in init pycocotools._mask
ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 80, got 88
```
By quickly searching on google it looks like version problems. 
I solved for now by `pip install pandas` 
that has automatically installed those versions but I don't know if it's correct as the numpy version is another. ( This is my first day on the clean-pvnet, so I didn't have time to test all the files )

```shell
pip install pandas
Collecting pandas
  Downloading pandas-1.2.2-cp37-cp37m-manylinux1_x86_64.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 7.2 MB/s 
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.7/site-packages (from pandas) (2.8.1)
Collecting numpy>=1.16.5
  Using cached numpy-1.20.1-cp37-cp37m-manylinux2010_x86_64.whl (15.3 MB)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas) (1.14.0)
Installing collected packages: numpy, pandas
  Attempting uninstall: numpy
    Found existing installation: numpy 1.16.4
    Uninstalling numpy-1.16.4:
      Successfully uninstalled numpy-1.16.4
Successfully installed numpy-1.20.1 pandas-1.2.2
```

**Comment by pengsida** [comment]
The code do not require a specific version of numpy.

**Comment by petrock99** [comment]
I hit this too and changed requirements.txt:

```
diff --git a/requirements.txt b/requirements.txt
index 9be8712..374ac73 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -3,7 +3,7 @@ numpy==1.16.4
 torchvision==0.2.1
 opencv-python==3.4.2.17
 tqdm==4.28.1
-pycocotools==2.0.0
+pycocotools==2.0.2
 matplotlib==2.2.2
 plyfile==0.6
 scikit-image==0.14.2

```
