### ISSUE TITLE
I run under windows system “cd ../nn " "python setup.py build_ext --inplace", failed and reported an error

### ISSUE THREAD

**Issue by WeiXie-wx** [zju3dv/clean-pvnet#184]
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
generating .\_ext.c
(already up-to-date)
the current directory is 'F:\\my_codes\\clean-pvnet\\lib\\csrc\\nn'
running build_ext
building '_ext' extension
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\include -IC:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tc_ext.c /Fo.\Release\_ext.obj       
_ext.c
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\libs /LIBPATH:C:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" stdc++.lib /EXPORT:PyInit__ext .\Release\_ext.obj src/nearest_neighborhood.cu.o "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\lib64/libcudart.so" /OUT:.\_ext.cp37-win_amd64.pyd /IMPLIB:.\Release\_ext.cp37-win_amd64.lib
LINK : fatal error LNK1181: 无法打开输入文件“stdc++.lib”
Traceback (most recent call last):
  File "C:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\lib\distutils\_msvccompiler.py", line 519, in link
    self.spawn([self.linker] + ld_args)
  File "C:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\lib\distutils\_msvccompiler.py", line 542, in spawn
    return super().spawn(cmd)
  File "C:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

**Comment by oppObject** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\xv_codes\clean-pvnet\lib\csrc\nn\setup.py", line 25, in <module>
    ffibuilder.compile(verbose=True)
  File "C:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\lib\site-packages\cffi\api.py", line 727, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "C:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\lib\site-packages\cffi\recompiler.py", line 1565, in recompile
    compiler_verbose, debug)
  File "C:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\lib\site-packages\cffi\ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "C:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\lib\site-packages\cffi\ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

**Comment by oppObject** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\my_codes\clean-pvnet\lib\csrc\nn\setup.py", line 25, in <module>
    ffibuilder.compile(verbose=True)
  File "C:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\lib\site-packages\cffi\api.py", line 727, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "C:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\lib\site-packages\cffi\recompiler.py", line 1565, in recompile
    compiler_verbose, debug)
  File "C:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\lib\site-packages\cffi\ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "C:\CommonPrograms\Anaconda3\envs\HPE_rebuild2021\lib\site-packages\cffi\ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

**Comment by Lexie971102** [comment]
> 你能帮我解决吗？

请问这个问题你解决了吗？我也出现了这个问题
