### ISSUE TITLE
Custom data training

### ISSUE THREAD

**Issue by KAOeric** [zju3dv/clean-pvnet#193]
I had create the data with that you shared above (https://github.com/F2Wang/ObjectDatasetTools) ，when i start to training with command **python run.py --type custom**, it got some error like this 
Traceback (most recent call last):
  File "run.py", line 276, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 222, in run_custom
    handle_custom_dataset.custom_to_coco(data_root)
  File "/home/m0807162/clean-pvnet/tools/handle_custom_dataset.py", line 89, in custom_to_coco
    renderer = OpenGLRenderer(model_path)
  File "/home/m0807162/clean-pvnet/lib/utils/linemod/opengl_renderer.py", line 21, in __init__
    self.model = self.load_ply(self.ply_path)
  File "/home/m0807162/clean-pvnet/lib/utils/linemod/opengl_renderer.py", line 42, in load_ply
    line = f.readline().rstrip('\n').rstrip('\r') # Strip the newline character(s)
  File "/home/m0807162/anaconda3/envs/pvnet/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 297: invalid start byte
Could anyone help me to solve this problem, thanks!

**Comment by pengsida** [comment]
It  seems that the code does not work on the model from https://github.com/F2Wang/ObjectDatasetTools

**Comment by Acero522** [comment]
I solve this problem today. It's about ply file's formt, there are two versions of the file format, one in ASCII, the other in binary. 
You can import ply file in blender and export it with 'format: ascii'.

**Comment by KAOeric** [comment]
Thanks @Acero522 I already solve it, but there is an another question, Did you train your custom dataset?
