### ISSUE TITLE
train_net.py

### ISSUE THREAD

**Issue by dcf123-ff** [zju3dv/clean-pvnet#213]
/home/dcf/anaconda3/envs/pvnet-clean/bin/python3.7 /home/dcf/桌面/clean-pvnet-master/train_net.py 
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!

Traceback (most recent call last):
  File "/home/dcf/桌面/clean-pvnet-master/train_net.py", line 57, in <module>
    main()
  File "/home/dcf/桌面/clean-pvnet-master/train_net.py", line 53, in main
    train(cfg, network)
  File "/home/dcf/桌面/clean-pvnet-master/train_net.py", line 28, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/home/dcf/桌面/clean-pvnet-master/lib/train/trainers/trainer.py", line 31, in train
    for iteration, batch in enumerate(data_loader):
  File "/home/dcf/anaconda3/envs/pvnet-clean/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/dcf/anaconda3/envs/pvnet-clean/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/dcf/anaconda3/envs/pvnet-clean/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/dcf/anaconda3/envs/pvnet-clean/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "lib/datasets/linemod/pvnet.py", line 40, in __getitem__
    index, height, width = index_tuple
TypeError: cannot unpack non-iterable int object

您好，这个问题我不知道怎么解决，希望可以得到您的帮助，非常感谢您.

**Comment by pengsida** [comment]
请问你有改过代码吗？
