### ISSUE TITLE
Visualize with a detector出錯！

### ISSUE THREAD

**Issue by BoBoINVIDICUS** [zju3dv/clean-pvnet#232]
當我運行命令行：python run.py --type detector_pvnet --cfg_file configs/ct_linemod.yaml 出錯！
Traceback (most recent call last):
  File "run.py", line 282, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 239, in run_detector_pvnet
    network = make_network(cfg).cuda()
  File "/home/akon/clean-pvnet/lib/networks/make_network.py", line 34, in make_network
    return imp.load_source(module, path).get_network(cfg)
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.1/lib/python3.7/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "lib/networks/ct_pvnet/__init__.py", line 1, in <module>
    from .res import get_network as get_res
  File "lib/networks/ct_pvnet/res.py", line 2, in <module>
    from lib.networks.ct.dla import get_network as get_pose_net
  File "/home/akon/clean-pvnet/lib/networks/ct/__init__.py", line 1, in <module>
    from .dla import get_network as get_dla
  File "/home/akon/clean-pvnet/lib/networks/ct/dla.py", line 2, in <module>
    from .dla_dcn import DLASeg
  File "/home/akon/clean-pvnet/lib/networks/ct/dla_dcn.py", line 16, in <module>
    from lib.networks.dcn_v2 import DCN
  File "/home/akon/clean-pvnet/lib/networks/dcn_v2.py", line 13, in <module>
    from lib.csrc.dcn_v2 import _ext as _backend
ImportError: /home/akon/clean-pvnet/lib/csrc/dcn_v2/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_10E
請問是什麼原因呢？

**Comment by pengsida** [comment]
看起来是dcn编译有问题。
