### ISSUE TITLE
KeyError: 'Non-existent config key: train.sampler'

### ISSUE THREAD

**Issue by g185211** [zju3dv/clean-pvnet#25]
Hi, thanks for your work. When I ran "python train_net.py --cfg_file configs/linemod.yaml model mycat cls_type cat", I met the followig error:

Traceback (most recent call last):
  File "train_net.py", line 1, in <module>
    from lib.config import cfg, args
  File "/home/yang/clean-pvnet-master/lib/config/__init__.py", line 1, in <module>
    from .config import cfg, args
  File "/home/yang/clean-pvnet-master/lib/config/config.py", line 147, in <module>
    cfg = make_cfg(args)
  File "/home/yang/clean-pvnet-master/lib/config/config.py", line 130, in make_cfg
    cfg.merge_from_file(args.cfg_file)
  File "/home/yang/anaconda3/envs/pvnet/lib/python3.6/site-packages/yacs/config.py", line 171, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/yang/anaconda3/envs/pvnet/lib/python3.6/site-packages/yacs/config.py", line 175, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/yang/anaconda3/envs/pvnet/lib/python3.6/site-packages/yacs/config.py", line 401, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/yang/anaconda3/envs/pvnet/lib/python3.6/site-packages/yacs/config.py", line 392, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: train.sampler'

I don't know how to solve it. And I am looking forward your reply. Thanks!

**Comment by pengsida** [comment]
Hi, I have updated the code.

**Comment by g185211** [comment]
Thanks for your help, I have solved above error.
However, I met a new error:

(pvnet) yang@A4:~/clean-pvnet-master$ python train_net.py --cfg_file configs/linemod.yaml model mycat cls_type cat
loading annotations into memory...
Done (t=0.08s)
creating index...
index created!
Traceback (most recent call last):
  File "train_net.py", line 57, in <module>
    main()
  File "train_net.py", line 53, in main
    train(cfg, network)
  File "train_net.py", line 22, in train
    train_loader = make_data_loader(cfg, is_train=True, max_iter=cfg.ep_iter)
  File "/home/yang/clean-pvnet-master/lib/datasets/make_dataset.py", line 72, in make_data_loader
    dataset = make_dataset(cfg, dataset_name, transforms, is_train)
  File "/home/yang/clean-pvnet-master/lib/datasets/make_dataset.py", line 34, in make_dataset
    dataset = dataset(**args)
TypeError: __init__() got an unexpected keyword argument 'cfg'

I tried for long time, but I didn't find the answer.

**Comment by pengsida** [comment]
I have fixed the bug.

**Comment by g185211** [comment]
(pvnet) yang@A4:~/clean-pvnet-master$ python train_net.py --cfg_file configs/linemod.yaml model mycat cls_type cat
loading annotations into memory...
Done (t=0.10s)
creating index...
index created!
loading annotations into memory...
Done (t=2.14s)
creating index...
index created!
loading annotations into memory...
Done (t=0.05s)
creating index...
index created!
Traceback (most recent call last):
  File "train_net.py", line 57, in <module>
    main()
  File "train_net.py", line 53, in main
    train(cfg, network)
  File "train_net.py", line 28, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/home/yang/clean-pvnet-master/lib/train/trainers/trainer.py", line 32, in train
    for iteration, batch in enumerate(data_loader):
  File "/home/yang/anaconda3/envs/pvnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/yang/anaconda3/envs/pvnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 606, in _process_next_batch
    raise Exception("KeyError:" + batch.exc_msg)
Exception: KeyError:Traceback (most recent call last):
  File "/home/yang/anaconda3/envs/pvnet/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/yang/clean-pvnet-master/lib/datasets/collate_batch.py", line 35, in pvnet_collator
    if 'pose_test' not in batch[0]['meta']:
KeyError: 'meta'

**Comment by pengsida** [comment]
It is fixed.

**Comment by g185211** [comment]
Thank you very much! It's OK

**Comment by pengsida** [comment]
Thank you!
