### ISSUE TITLE
cffi.error.VerificationError: LinkError: command '/usr/bin/gcc' failed with exit code 1

### ISSUE THREAD

**Issue by assia855** [zju3dv/clean-pvnet#270]
Thanks for this awesome project. I would like to test but I can't compile nn. I have this error while compling :
cd ../nn
python setup.py build_ext --inplace

Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    ffibuilder.compile(verbose=True)
  File "/home/asp/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/asp/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/asp/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/asp/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command '/usr/bin/gcc' failed with exit code 1

thanks for any suggestion to solve this error.

**Comment by assia855** [comment]
I solve it by adding this two lines to my bashrc file:

export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:$LD_LIBRARY_PATH
export PATH=/usr/local/cuda-9.0/bin:$PATH

and I recompile cuda extensions under lib/csrc.
