### ISSUE TITLE
ValueError: shapes (8,4) and (3,3) not aligned: 4 (dim 1) != 3 (dim 0)

### ISSUE THREAD

**Issue by assia855** [zju3dv/clean-pvnet#272]
Hi I prepare my dataset following the repo ObjectDatsetsTools and while preparing the data I got this error: 

`python run.py --type custom 
  0%|                                                  | 0/1069 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 276, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 222, in run_custom
    handle_custom_dataset.custom_to_coco(data_root)
  File "/home/asp/Documents/clean-pvnet/tools/handle_custom_dataset.py", line 110, in custom_to_coco
    img_id, ann_id = record_ann(model_meta, img_id, ann_id, images, annotations)
  File "/home/asp/Documents/clean-pvnet/tools/handle_custom_dataset.py", line 67, in record_ann
    corner_2d = base_utils.project(corner_3d, K, pose)
  File "/home/asp/Documents/clean-pvnet/lib/utils/base_utils.py", line 24, in project
    xyz = np.dot(xyz, K.T)
ValueError: shapes (8,4) and (3,3) not aligned: 4 (dim 1) != 3 (dim 0)
`
Please any suggestion to overcome this error. Thanks in advance.

**Comment by assia855** [comment]
Hi it's me again, I think I find a solution by adding this line: `xyx = xyz[:,:3]` in lib/utils/base_utils.py  now the project function looks like that: 

def project(xyz, K, RT):
xyz = np.dot(xyz, RT[:,:3].T) + RT[:,3:].T
print(xyz)
xyz = xyz[:,:3]
xyz = np.dot(xyz, K.T)
xy = xyz[:, :2] / xyz[:, 2:]
return xy

**Comment by assia855** [comment]
This solution doesn't seem to be a good solution because after launching the training  for some epochs the training crash with this error: 
![Capture d’écran du 2023-09-25 11-50-56](https://github.com/zju3dv/clean-pvnet/assets/62453226/2db9cf14-d5fe-452f-aff6-66bfa6cb3185)

**Comment by monajalal** [comment]
@assia855 your bote_loss, seg_loss, and loss are all nan

**Comment by pengsida** [comment]
It seems that your data format is incorrect.

**Comment by monajalal** [comment]
@pengsida I am using same exact data as you have instructed (Linemod)

**Comment by zhangleeeeee** [comment]
我也遇到了这个问题，报错一模一样，请问您解决了没有？
