### ISSUE TITLE
error in test with Test with the uncertainty-driven PnP

### ISSUE THREAD

**Issue by monajalal** [zju3dv/clean-pvnet#279]
```
(clean-pvnet) mona@ada:~/clean-pvnet$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./lib/csrc/uncertainty_pnp/lib
(clean-pvnet) mona@ada:~/clean-pvnet$ python run.py --type evaluate --cfg_file configs/linemod.yaml model cat cls_type cat test.un_pnp True
Load model: data/model/pvnet/cat/199.pth
loading annotations into memory...
Done (t=0.15s)
creating index...
index created!
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
  0%|                                                                                                                                                                              | 0/1002 [00:00<?, ?it/s]/home/mona/clean-pvnet/lib/csrc/uncertainty_pnp/un_pnp_utils.py:24: ComplexWarning: Casting complex values to real discards the imaginary part
  weights_2d = weights_2d.astype(np.float64)
  2%|███▏                                                                                                                                                                 | 19/1002 [00:01<01:22, 11.92it/s]
Traceback (most recent call last):
  File "/home/mona/clean-pvnet/run.py", line 276, in <module>
    globals()['run_'+args.type]()
  File "/home/mona/clean-pvnet/run.py", line 79, in run_evaluate
    evaluator.evaluate(output, batch)
  File "lib/evaluators/linemod/pvnet.py", line 186, in evaluate
    pose_pred = self.uncertainty_pnp(kpt_3d, kpt_2d, var, K)
  File "lib/evaluators/linemod/pvnet.py", line 130, in uncertainty_pnp
    pose_pred = un_pnp_utils.uncertainty_pnp(kpt_2d, weights, kpt_3d, K)
  File "/home/mona/clean-pvnet/lib/csrc/uncertainty_pnp/un_pnp_utils.py", line 43, in uncertainty_pnp
    init_rt = np.ascontiguousarray(np.concatenate([R_exp, t], 0), np.float64)
ValueError: zero-dimensional arrays cannot be concatenated

```

More specifically:

```
(clean-pvnet) mona@ada:~/clean-pvnet$ python run.py --type evaluate --cfg_file configs/linemod.yaml model cat cls_type cat test.un_pnp True
Load model: data/model/pvnet/cat/199.pth
loading annotations into memory...
Done (t=0.12s)
creating index...
index created!
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
  0%|                                                                                                                                                                              | 0/1002 [00:00<?, ?it/s]/home/mona/clean-pvnet/lib/csrc/uncertainty_pnp/un_pnp_utils.py:24: ComplexWarning: Casting complex values to real discards the imaginary part
  weights_2d = weights_2d.astype(np.float64)
R_exp.ndim:  2
t.ndim:  2
  0%|▏                                                                                                                                                                     | 1/1002 [00:00<11:53,  1.40it/s]R_exp.ndim:  2
t.ndim:  2
R_exp.ndim:  2
t.ndim:  2
R_exp.ndim:  2
t.ndim:  2
  0%|▋                                                                                                                                                                     | 4/1002 [00:00<02:43,  6.09it/s]R_exp.ndim:  2
t.ndim:  2
R_exp.ndim:  2
t.ndim:  2
R_exp.ndim:  2
t.ndim:  2
  1%|█▏                                                                                                                                                                    | 7/1002 [00:00<01:38, 10.09it/s]R_exp.ndim:  2
t.ndim:  2
R_exp.ndim:  2
t.ndim:  2
R_exp.ndim:  2
t.ndim:  2
  1%|█▋                                                                                                                                                                   | 10/1002 [00:01<01:11, 13.84it/s]R_exp.ndim:  2
t.ndim:  2
R_exp.ndim:  2
t.ndim:  2
R_exp.ndim:  2
t.ndim:  2
  1%|██▏                                                                                                                                                                  | 13/1002 [00:01<00:56, 17.43it/s]R_exp.ndim:  2
t.ndim:  2
R_exp.ndim:  2
t.ndim:  2
R_exp.ndim:  2
t.ndim:  2
  2%|██▋                                                                                                                                                                  | 16/1002 [00:01<00:51, 19.27it/s]R_exp.ndim:  2
t.ndim:  2
R_exp.ndim:  2
t.ndim:  2
R_exp.ndim:  2
t.ndim:  2
  2%|███▏                                                                                                                                                                 | 19/1002 [00:01<01:18, 12.57it/s]
Traceback (most recent call last):
  File "/home/mona/clean-pvnet/run.py", line 276, in <module>
    globals()['run_'+args.type]()
  File "/home/mona/clean-pvnet/run.py", line 79, in run_evaluate
    evaluator.evaluate(output, batch)
  File "lib/evaluators/linemod/pvnet.py", line 186, in evaluate
    pose_pred = self.uncertainty_pnp(kpt_3d, kpt_2d, var, K)
  File "lib/evaluators/linemod/pvnet.py", line 130, in uncertainty_pnp
    pose_pred = un_pnp_utils.uncertainty_pnp(kpt_2d, weights, kpt_3d, K)
  File "/home/mona/clean-pvnet/lib/csrc/uncertainty_pnp/un_pnp_utils.py", line 43, in uncertainty_pnp
    print("R_exp.ndim: ", R_exp.ndim)
AttributeError: 'NoneType' object has no attribute 'ndim'

```

**Comment by monajalal** [comment]
@pengsida would you please be able to help me a bit with this? Thank you so much

**Comment by pengsida** [comment]
It seems that the output of the network is incorrect.

**Comment by 1230678** [comment]
请问您解决了吗，我现在遇到了同样的问题 @monajalal
