### ISSUE TITLE
  File "lib/evaluators/tless_test/pvnet.py", line 42, in __init__     model_info = yaml.load(open(os.path.join(model_dir, 'models_info.yml'))) TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by monajalal** [zju3dv/clean-pvnet#280]
```
(clean-pvnet) mona@ada:~/clean-pvnet$ python run.py --type evaluate --cfg_file configs/tless/tless_01.yaml
/home/mona/anaconda3/envs/clean-pvnet/lib/python3.10/site-packages/imgaug/imgaug.py:184: DeprecationWarning: Function `ContrastNormalization()` is deprecated. Use `imgaug.contrast.LinearContrast` instead.
  warn_deprecated(msg, stacklevel=3)
loading annotations into memory...
Done (t=3.72s)
creating index...
index created!
loading annotations into memory...
Done (t=3.82s)
creating index...
index created!
Traceback (most recent call last):
  File "/home/mona/clean-pvnet/run.py", line 276, in <module>
    globals()['run_'+args.type]()
  File "/home/mona/clean-pvnet/run.py", line 74, in run_evaluate
    evaluator = make_evaluator(cfg)
  File "/home/mona/clean-pvnet/lib/evaluators/make_evaluator.py", line 19, in make_evaluator
    return _evaluator_factory(cfg)
  File "/home/mona/clean-pvnet/lib/evaluators/make_evaluator.py", line 11, in _evaluator_factory
    evaluator = imp.load_source(module, path).Evaluator(cfg.result_dir)
  File "lib/evaluators/tless_test/pvnet.py", line 42, in __init__
    model_info = yaml.load(open(os.path.join(model_dir, 'models_info.yml')))
TypeError: load() missing 1 required positional argument: 'Loader'

```

**Comment by monajalal** [comment]
changing

`model_info = yaml.load(open(os.path.join(model_dir, 'models_info.yml')))`

to

`model_info = yaml.load(open(os.path.join(model_dir, 'models_info.yml')), Loader=yaml.FullLoader)`

seems to have fixed the issue


```
(clean-pvnet) mona@ada:~/clean-pvnet$ python run.py --type evaluate --cfg_file configs/tless/tless_01.yaml
/home/mona/anaconda3/envs/clean-pvnet/lib/python3.10/site-packages/imgaug/imgaug.py:184: DeprecationWarning: Function `ContrastNormalization()` is deprecated. Use `imgaug.contrast.LinearContrast` instead.
  warn_deprecated(msg, stacklevel=3)
loading annotations into memory...
Done (t=3.75s)
creating index...
index created!
loading annotations into memory...
Done (t=3.79s)
creating index...
index created!
yaml file path is:  data/tless/models_cad/models_info.yml
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2927/2927 [03:16<00:00, 14.87it/s]
vsd metric: 0.0
adi metric: 0.0009953550099535502
5 cm 5 degree metric: 0.0

```
