### ISSUE TITLE
KeyError: 'mask'

### ISSUE THREAD

**Issue by kashyap92** [zju3dv/clean-pvnet#29]
Thank you so much for sharing the code and model for tless. 
While training tless dataset, i am facing this error.  Could you please help me with this?

Traceback (most recent call last):
  File "train_net.py", line 57, in <module>
    main()
  File "train_net.py", line 53, in main
    train(cfg, network)
  File "train_net.py", line 35, in train
    trainer.val(epoch, val_loader, evaluator, recorder)
  File "/datasets/Mahesh_kashyap/pvnet-clean/clean-pvnet/lib/train/trainers/trainer.py", line 82, in val
    output, loss, loss_stats, image_stats = self.network(batch)
  File "/home/belakavadi/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/belakavadi/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/belakavadi/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/belakavadi/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/belakavadi/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/belakavadi/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/train/trainers/pvnet.py", line 24, in forward
    weight = batch['mask'][:, None].float()
KeyError: 'mask'

Regards,
Mahesh

**Comment by pengsida** [comment]
What is your command?
I can train the network with `python train_net.py --cfg_file configs/tless/tless_01.yaml model tmp`.

**Comment by firstdeep** [comment]
> What is your command?
> I can train the network with `python train_net.py --cfg_file configs/tless/tless_01.yaml model tmp`.

I have the same issue.

My command is = python train_net.py --cfg_file configs/tless/tless_01.yaml model tless_models/tless_01 eval_ep 1

There seems to be a problem with reading data in the area of evaluation.
https://github.com/zju3dv/clean-pvnet/blob/master/train_net.py#L35

**Comment by pengsida** [comment]
I fixed the bug.

**Comment by firstdeep** [comment]
@pengsida 

Thanks for fix the bug.

I have a question.
The test data for A is 504. 
But I wonder why there are 1,008 images that are actually loaded.

![image](https://user-images.githubusercontent.com/52238766/76194282-345e5500-6229-11ea-9a1b-30305e5fdc8c.png)

Thanks for reply

**Comment by pengsida** [comment]
I evaluate every objects on the whole dataset.
1,008 is the number of images containing a specific object in the dataset.

**Comment by Ji-Hu** [comment]
@pengsida 

Thank you for sharing your great achievements.

I'd like to ask you a few questions.

#1. 
https://github.com/zju3dv/clean-pvnet/blob/master/lib/evaluators/tless_test/pvnet.py#L43
In case of ADD, I think it will be judged that it is correct if it is within 10% of the diameter. Why is there a reason to divide the diameter by 1000? 

I also want to ask about the difference between adi_metrix and add_metrix.

#2. 
I wonder if there is a reason for the evaluation of the input image by cropping only the test_object part (input size = 256 * 256) 

I think we should put the original test image(image size = 540 * 720 / Not cropping) in the input.

**Comment by pengsida** [comment]
1. The unit of the object diameter is mm. 
2. adi is a variant of add for symmetric objects.
3. To handle multiple instances.

**Comment by kashyap92** [comment]
Hello @pengsida ,
Thank you for your response. 'KeyError: 'mask' is now resolved'. 
However, after 4 epoch i am facing new error now.

My training command is : python train_net.py --cfg_file configs/tless/tless_01.yaml

Error:
Traceback (most recent call last):
  File "train_net.py", line 57, in <module>
    main()
  File "train_net.py", line 53, in main
    train(cfg, network)
  File "train_net.py", line 35, in train
    trainer.val(epoch, val_loader, evaluator, recorder)
  File "/datasets/Mahesh_kashyap/PoseEst/pvnet-clean/clean-pvnet/lib/train/trainers/trainer.py", line 82, in val
    output, loss, loss_stats, image_stats = self.network(batch)
  File "/home/belakavadi/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/belakavadi/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/home/belakavadi/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/belakavadi/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 67, in gather
    return gather_map(outputs)
  File "/home/belakavadi/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/belakavadi/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: zip argument #1 must support iteration****

Could you please help me resolved this?

Regards,
Mahesh kashyap.

**Comment by pengsida** [comment]
I have fixed the bug.
You could directly test the evaluation code using `python train_net.py --test --cfg_file configs/tless/tless_01.yaml`.
