### ISSUE TITLE
keyError 'CustomTrain' from dataset_catalog.py and TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by firstdeep** [zju3dv/clean-pvnet#30]
Hello

There is an error in your code.

1)
Traceback (most recent call last):
attrs = DatasetCatalog.dataset_attrs[name]
KeyError: 'CustomTrain'

https://github.com/zju3dv/clean-pvnet/blob/master/lib/datasets/dataset_catalog.py#L74

The corresponding code is missing.
        'CustomTrain': {
            'id': 'linemod',
            'data_root': 'data/custom',
            'ann_file': 'data/custom/train.json',
            'split': 'train'
        },

2)
my command is = python train_net.py --cfg_file configs/linemod.yaml train.dataset CustomTrain test.dataset CustomTrain model tless_06 train.batch_size 8 eval_ep 20 train.epoch 201

Traceback (most recent call last):
  File "train_net.py", line 67, in <module>
    main()
  File "train_net.py", line 63, in main
    train(cfg, network) # @ go line 28
  File "train_net.py", line 37, in train
    trainer.train(epoch, train_loader, optimizer, recorder) # Go to train --> lib - train - trainers - trainer.py
  File "/home/hwanglab/PycharmProjects/clean-pvnet/lib/train/trainers/trainer.py", line 33, in train
    for iteration, batch in enumerate(data_loader): # get Datasets from lib - datasets - tless_train - pvnet.py - def __getitem__
  File "/home/hwanglab/anaconda3/envs/pvnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/hwanglab/anaconda3/envs/pvnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/hwanglab/anaconda3/envs/pvnet/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/hwanglab/anaconda3/envs/pvnet/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "lib/datasets/linemod/pvnet.py", line 41, in __getitem__
    index, height, width = index_tuple
**TypeError: 'int' object is not iterable**

i'm having trouble using custom data.
I'd appreciate it if you could look at the code once.

thank you 

david

**Comment by pengsida** [comment]
Thank you so much for pointing out these errors.
Previously I merged the linemod code and tless code, which introduced some errors.

**Comment by firstdeep** [comment]
Hello @pengsida ,
Thank you for your response. 
But there was another problem.

My training command is : python train_net.py --cfg_file configs/linemod.yaml train.dataset CustomTrain model tless_06 train.batch_size 4

custom dataset input size == 400 * 400 * 3 

Traceback (most recent call last):
  File "train_net.py", line 67, in <module>
    main()
  File "train_net.py", line 63, in main
    train(cfg, network) # @ go line 28
  File "train_net.py", line 37, in train
    trainer.train(epoch, train_loader, optimizer, recorder) # Go to train --> lib - train - trainers - trainer.py
  File "/home/hwanglab/PycharmProjects/clean-pvnet/lib/train/trainers/trainer.py", line 49, in train
    output, loss, loss_stats, image_stats = self.network(batch)
  File "/home/hwanglab/anaconda3/envs/pvnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hwanglab/anaconda3/envs/pvnet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/hwanglab/anaconda3/envs/pvnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/train/trainers/pvnet.py", line 16, in forward
    output = self.net(batch['inp'])
  File "/home/hwanglab/anaconda3/envs/pvnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/pvnet/resnet18.py", line 73, in forward
    x2s, x4s, x8s, x16s, x32s, xfc = self.resnet18_8s(x)
  File "/home/hwanglab/anaconda3/envs/pvnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/pvnet/resnet.py", line 201, in forward
    x = self.conv1(x)
  File "/home/hwanglab/anaconda3/envs/pvnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hwanglab/anaconda3/envs/pvnet/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 64 3 7 7, expected input[4, 328, 280, 3] to have 3 channels, but got 328 channels instead

I'd appreciate it if you could check the code one more time.

Thanks 

david.

**Comment by pengsida** [comment]
I fixed the bug just now.
If you want to train the tless objects, you might need to use the tless code, which has a corresponding data augmentation, since the training data is synthetic in tless.

**Comment by firstdeep** [comment]
Thank you for fixing the bug.!!!

I know that tless data needs a synthetic image. 
Therefore, I have already synthesized the tless datasets in advance and have been training with custom.

like that
/home/hwanglab/PycharmProjects/clean-pvnet-standard/data/custom/rgb/0.jpg


I want to use your tless code, but I am having a hard time because the input size of the training image is different. 
If I want to create something related to new data annotation file without using the pre-supplied annotation file,

https://github.com/zju3dv/clean-pvnet/blob/master/run.py#L176
can i use the code on the link above, right?

Thank you for your reply and kindness.

I will refer to your research and bring great results.

Thank you very much.

Regard,
David.

**Comment by pengsida** [comment]
1. What do you mean by "the input size of the training image is different".
2. I cannot provide the concrete procedure to generate the training using https://github.com/zju3dv/clean-pvnet/blob/master/run.py#L176, since I do not have an GUI environment to check the generated data currently. I have uploaded all the training data I used for the  training on the tless dataset, so maybe you can directly use the data.

**Comment by firstdeep** [comment]
1. The answer to the first question was that I misunderstood the dataset.

Thank you for your answer.

Thank you very much

David
