### ISSUE TITLE
TLess dataset problem

### ISSUE THREAD

**Issue by fransonf** [zju3dv/clean-pvnet#37]
Hello! I downloaded the repo, datasets and followed the installation guide here on the repo but do not manage to run the `python train_net.py --cfg_file configs/tless/tless_01.yaml` command. I attach the terminal output. Just like the error says there are missing files.

When pressing the 5:th link under the list of datasets it takes me to a list of 14 items and I chose the first i.e. "tlessaa". Do I need them all? Because the one I chose does not contain `train_primesense` which the code tries to execute.

Thanks in advance!

python train_net.py --cfg_file configs/tless/tless_01.yaml
loading annotations into memory...
Done (t=3.07s)
creating index...
index created!
lib/evaluators/tless_test/pvnet.py:42: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  model_info = yaml.load(open(os.path.join(model_dir, 'models_info.yml')))
/home/franswed/anaconda3/envs/pvnet/lib/python3.7/site-packages/imgaug/imgaug.py:184: DeprecationWarning: Function `ContrastNormalization()` is deprecated. Use `imgaug.contrast.LinearContrast` instead.
  warn_deprecated(msg, stacklevel=3)
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
loading annotations into memory...
Traceback (most recent call last):
  File "train_net.py", line 57, in <module>
    main()
  File "train_net.py", line 53, in main
    train(cfg, network)
  File "train_net.py", line 22, in train
    train_loader = make_data_loader(cfg, is_train=True, max_iter=cfg.ep_iter)
  File "/home/franswed/Documents/MastersThesis2020/clean-pvnet-master/lib/datasets/make_dataset.py", line 73, in make_data_loader
    dataset = make_dataset(cfg, dataset_name, transforms, is_train)
  File "/home/franswed/Documents/MastersThesis2020/clean-pvnet-master/lib/datasets/make_dataset.py", line 32, in make_dataset
    dataset = dataset(**args)
  File "lib/datasets/tless_train/pvnet.py", line 46, in __init__
    self.other_obj_coco = COCO('data/tless/train_primesense/assets/train.json')
  File "/home/franswed/anaconda3/envs/pvnet/lib/python3.7/site-packages/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'data/tless/train_primesense/assets/train.json'

**Comment by pengsida** [comment]
You need them all. `cat tlessa* | tar xvf - -C .`

**Comment by fransonf** [comment]
Thanks.

**Comment by fransonf** [comment]
Sorry to bother you again but still can't get it to work. Do you have any idea what causes the error below? I downloaded them all and re-linked the dataset after calling `cat tlessa* | tar xvf - -C .`

python train_net.py --cfg_file configs/tless/tless_01.yaml

loading annotations into memory...
Done (t=2.97s)
creating index...
index created!
lib/evaluators/tless_test/pvnet.py:42: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  model_info = yaml.load(open(os.path.join(model_dir, 'models_info.yml')))
/home/franswed/anaconda3/envs/pvnet/lib/python3.7/site-packages/imgaug/imgaug.py:184: DeprecationWarning: Function `ContrastNormalization()` is deprecated. Use `imgaug.contrast.LinearContrast` instead.
  warn_deprecated(msg, stacklevel=3)
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
loading annotations into memory...
Done (t=3.60s)
creating index...
index created!
Traceback (most recent call last):
  File "train_net.py", line 57, in <module>
    main()
  File "train_net.py", line 53, in main
    train(cfg, network)
  File "train_net.py", line 28, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/home/franswed/Documents/MastersThesis2020/clean-pvnet-master/lib/train/trainers/trainer.py", line 32, in train
    for iteration, batch in enumerate(data_loader):
  File "/home/franswed/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/franswed/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/franswed/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/franswed/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "lib/datasets/tless_train/pvnet.py", line 111, in __getitem__
    img, kpt_2d, mask, bbox = self.get_training_img(img, kpt_2d, mask)
  File "lib/datasets/tless_train/pvnet.py", line 76, in get_training_img
    train_img = cv2.imread(self.bg_paths[np.random.randint(len(self.bg_paths))])
  File "mtrand.pyx", line 747, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1270, in numpy.random._bounded_integers._rand_int64
ValueError: low >= high

**Comment by pengsida** [comment]
It seems that you don't have SUN dataset.

![image](https://user-images.githubusercontent.com/11582122/76864219-b559c400-689b-11ea-8875-40febdf16860.png)

**Comment by fransonf** [comment]
Thanks again! I had it but called it "SUN2012pascalformat" instead of just "sun". Training is up and running now! Really appreciate the help.
