### ISSUE TITLE
Training is interrupted

### ISSUE THREAD

**Issue by fransonf** [zju3dv/clean-pvnet#44]
Every 5:th epoch, training using command `python train_net.py --cfg_file configs/tless/tless_01.yaml
` gets interrupted with RuntimeError from the `ransac_voting_gpu.py` file. Have you experienced this before? Do you know why it happens every fifth epoch?

eta: 0:00:18  epoch: 9  step: 4980  vote_loss: 0.0147  seg_loss: 0.0149  loss: 0.0296  data: 0.2134  batch: 0.5426  lr: 0.001000  max_mem: 2463
eta: 0:00:00  epoch: 9  step: 4999  vote_loss: 0.0141  seg_loss: 0.0147  loss: 0.0288  data: 0.2152  batch: 0.5443  lr: 0.001000  max_mem: 2463
eta: 0:00:00  epoch: 9  step: 5000  vote_loss: 0.0141  seg_loss: 0.0147  loss: 0.0289  data: 0.2197  batch: 0.5473  lr: 0.001000  max_mem: 2463
  0%|                                                                                   | 0/2927 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_net.py", line 58, in <module>
    main()
  File "train_net.py", line 54, in main
    train(cfg, network)
  File "train_net.py", line 35, in train
    trainer.val(epoch, val_loader, evaluator, recorder)
  File "/home/franswed/Documents/MastersThesis2020/clean-pvnet-master/lib/train/trainers/trainer.py", line 82, in val
    output, loss, loss_stats, image_stats = self.network.module(batch)
  File "/home/franswed/anaconda3/envs/pvnet2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/train/trainers/pvnet.py", line 16, in forward
    output = self.net(batch['inp'])
  File "/home/franswed/anaconda3/envs/pvnet2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/pvnet/resnet18.py", line 94, in forward
    self.decode_keypoint(ret)
  File "lib/networks/pvnet/resnet18.py", line 69, in decode_keypoint
    kpt_2d = ransac_voting_layer_v3(mask, vertex, 128, inlier_thresh=0.99, max_num=100)
  File "/home/franswed/Documents/MastersThesis2020/clean-pvnet-master/lib/csrc/ransac_voting/ransac_voting_gpu.py", line 190, in ransac_voting_layer_v3
    ATA=torch.matmul(normal.permute(0,2,1),normal)              # [vn,2,2]
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:450

**Comment by pengsida** [comment]
For every 5th epoch, it is because that the code evaluates the network every 5 epochs.
For the problem, I did not encounter this problem, so I do not know the reason.

**Comment by fransonf** [comment]
Solved it, thanks for answering.

**Comment by pengsida** [comment]
Could you tell me what caused this problem?

**Comment by fransonf** [comment]
I believe it was a mismatch between my CUDA version and pytorch/torchvision. From this https://pytorch.org/get-started/previous-versions/ I used command `conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch` to make it work.

**Comment by pengsida** [comment]
Thank you!
It is indeed a problem that we need to pay attention to.
