### ISSUE TITLE
error with cd ../uncertainty_pnp python setup.py build_ext --inplace 

### ISSUE THREAD

**Issue by zhuyazhi** [zju3dv/clean-pvnet#56]
hi~excuse me, I meet the error when i excute the command" python setup.py build_ext --inplace "
my gcc is 5.4.0

root@terminalf7980e54:/opt/data/private/clean-pvnet-master/lib/csrc/uncertainty_pnp# python setup.py build_ext --inplace
In file included from ./include/ceres/internal/autodiff.h:147:0,
                 from ./include/ceres/autodiff_cost_function.h:133,
                 from ./include/ceres/ceres.h:37,
                 from src/uncertainty_pnp.cpp:3:
./include/ceres/internal/fixed_array.h:38:26: fatal error: glog/logging.h: No such file or directory
compilation terminated.
generating ./_ext.c
(already up-to-date)
the current directory is '/opt/data/private/clean-pvnet-master/lib/csrc/uncertainty_pnp'
running build_ext
building '_ext' extension
gcc -pthread -B /root/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/include/python3.6m -c _ext.c -o ./_ext.o
gcc -pthread -shared -B /root/anaconda3/compiler_compat -L/root/anaconda3/lib -Wl,-rpath=/root/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_ext.o src/uncertainty_pnp.cpp.o ./lib/libceres.so ./lib/libglog.so -lstdc++ -o ./_ext.cpython-36m-x86_64-linux-gnu.so
gcc: error: src/uncertainty_pnp.cpp.o: No such file or directory
gcc: error: ./lib/libceres.so: No such file or directory
gcc: error: ./lib/libglog.so: No such file or directory
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/root/anaconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/root/anaconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/root/anaconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/root/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/root/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/root/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/root/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/root/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/root/anaconda3/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/root/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    ffibuilder.compile(verbose=True)
  File "/root/anaconda3/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/root/anaconda3/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/root/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/root/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

**Comment by pengsida** [comment]
You do not have `glog` and need to install it.
I have updated the REAME.md.
![image](https://user-images.githubusercontent.com/11582122/77813239-242bee00-70e2-11ea-970e-f7f84187669c.png)

**Comment by zhuyazhi** [comment]
ok,thank you~
