### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.utils.icp'

### ISSUE THREAD

**Issue by takuya-ikeda-tri** [zju3dv/clean-pvnet#58]
Hi, 
When I run "python run.py --type evaluate --cfg_file configs/linemod.yaml model cat cls_type cat test.icp True".

I faced the below error,
```
Traceback (most recent call last):
  File "run.py", line 226, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 74, in run_evaluate
    evaluator = make_evaluator(cfg)
  File "/home/takuya/Project/deep_learning/clean-pvnet/lib/evaluators/make_evaluator.py", line 19, in make_evaluator
    return _evaluator_factory(cfg)
  File "/home/takuya/Project/deep_learning/clean-pvnet/lib/evaluators/make_evaluator.py", line 11, in _evaluator_factory
    evaluator = imp.load_source(module, path).Evaluator(cfg.result_dir)
  File "/home/takuya/Project/deep_learning/clean-pvnet/pvnet-env/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "lib/evaluators/linemod/pvnet.py", line 12, in <module>
    from lib.utils.icp.icp_refiner.build import ext_
ModuleNotFoundError: No module named 'lib.utils.icp'
```
I could not see the /lib/utils/icp directory and icp_refiner.py.
Could you teach me how to solve it?

**Comment by pengsida** [comment]
I fixed this bug and updated the code.

**Comment by takuya-ikeda-tri** [comment]
Thanks!
