### ISSUE TITLE
libceres.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by DanelBanel** [zju3dv/clean-pvnet#60]
When running 
`/data/people/tjonsda/Projects/pvnet_clean/train_net.py --cfg_file configs/custom.yaml train.batch_size 4` and created the custom dataset from the instructions (which shoudlnt matter here anyway)

i get the following error 
`Traceback (most recent call last):
  File "/data/people/tjonsda/Projects/pvnet_clean/train_net.py", line 57, in <module>
    main()
  File "/data/people/tjonsda/Projects/pvnet_clean/train_net.py", line 53, in main
    train(cfg, network)
  File "/data/people/tjonsda/Projects/pvnet_clean/train_net.py", line 17, in train
    evaluator = make_evaluator(cfg)
  File "/data/people/tjonsda/Projects/pvnet_clean/lib/evaluators/make_evaluator.py", line 19, in make_evaluator
    return _evaluator_factory(cfg)
  File "/data/people/tjonsda/Projects/pvnet_clean/lib/evaluators/make_evaluator.py", line 11, in _evaluator_factory
    evaluator = imp.load_source(module, path).Evaluator(cfg.result_dir)
  File "/data/people/tjonsda/anaconda3/envs/pvnet-clean/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "lib/evaluators/custom/pvnet.py", line 12, in <module>
    from lib.csrc.uncertainty_pnp import un_pnp_utils
  File "/data/people/tjonsda/Projects/pvnet_clean/lib/csrc/uncertainty_pnp/un_pnp_utils.py", line 1, in <module>
    from lib.csrc.uncertainty_pnp._ext import lib, ffi
ImportError: libceres.so.2: cannot open shared object file: No such file or directory`

I have ran 
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./lib/csrc/uncertainty_pnp/lib` as stating in the readme and also followed the steps from errors in the original PVNet, but cant to seem it work.

**Comment by pengsida** [comment]
If you do not run the command at $ROOT, you need to change `./lib/csrc/uncertainty_pnp/lib` to `/path/to/clean-pvnet/lib/csrc/uncertainty_pnp/lib`.
