### ISSUE TITLE
test un-pnp

### ISSUE THREAD

**Issue by 545464598** [zju3dv/clean-pvnet#68]
你好，请问，这是什么问题呀？
Load model: data/model/pvnet/cat/199.pth
loading annotations into memory...
Done (t=0.12s)
creating index...
index created!
Traceback (most recent call last):
  File "run.py", line 227, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 75, in run_evaluate
    evaluator = make_evaluator(cfg)
  File "/home/yanhao/path/to/clean-pvnet/lib/evaluators/make_evaluator.py", line 27, in make_evaluator
    return _evaluator_factory(cfg)
  File "/home/yanhao/path/to/clean-pvnet/lib/evaluators/make_evaluator.py", line 16, in _evaluator_factory
    evaluator = imp.load_source(module, path).Evaluator(cfg.result_dir)
  File "/home/yanhao/anaconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "lib/evaluators/linemod/pvnet.py", line 13, in <module>
    from lib.csrc.uncertainty_pnp import un_pnp_utils
  File "/home/yanhao/path/to/clean-pvnet/lib/csrc/uncertainty_pnp/un_pnp_utils.py", line 1, in <module>
    from lib.csrc.uncertainty_pnp._ext import lib, ffi
ModuleNotFoundError: No module named 'lib.csrc.uncertainty_pnp._ext'

**Comment by 545464598** [comment]
上面的问题更换了python run.py --type evaluate --cfg_file configs/linemod.yaml model cat cls_type cat test.un_pnp True解决了。但是出现了新的bug
Load model: data/model/pvnet/cat/199.pth
loading annotations into memory...
Done (t=0.11s)
creating index...
index created!
Traceback (most recent call last):
  File "run.py", line 228, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 76, in run_evaluate
    evaluator = make_evaluator(cfg)
  File "/home/yanhao/path/to/clean-pvnet/lib/evaluators/make_evaluator.py", line 19, in make_evaluator
    return _evaluator_factory(cfg)
  File "/home/yanhao/path/to/clean-pvnet/lib/evaluators/make_evaluator.py", line 11, in _evaluator_factory
    evaluator = imp.load_source(module, path).Evaluator(cfg.result_dir)
  File "/home/yanhao/anaconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "lib/evaluators/linemod/pvnet.py", line 19, in <module>
    from transforms3d.quaternions import mat2quat, quat2mat
ModuleNotFoundError: No module named 'transforms3d'

**Comment by 545464598** [comment]
1.
