### ISSUE TITLE
Uncertainty pnp: ImportError: libceres.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by toblo956** [zju3dv/clean-pvnet#81]
Hi, I am trying to run uncertainty_pnp, with commands run.py --type evaluate --cfg_file configs/custom.yaml test.un_pnp True and I get this error:

Traceback (most recent call last):
  File "/data/people/lofgrto/Projects/pvnet_clean/run.py", line 230, in <module>
    globals()['run_'+args.type]()
  File "/data/people/lofgrto/Projects/pvnet_clean/run.py", line 74, in run_evaluate
    evaluator = make_evaluator(cfg)
  File "/data/people/lofgrto/Projects/pvnet_clean/lib/evaluators/make_evaluator.py", line 19, in make_evaluator
    return _evaluator_factory(cfg)
  File "/data/people/lofgrto/Projects/pvnet_clean/lib/evaluators/make_evaluator.py", line 11, in _evaluator_factory
    evaluator = imp.load_source(module, path).Evaluator(cfg.result_dir)
  File "/data/people/lofgrto/anaconda3/envs/pvnet-clean/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "lib/evaluators/custom/pvnet.py", line 16, in <module>
    from lib.csrc.uncertainty_pnp import un_pnp_utils
  File "/data/people/lofgrto/Projects/pvnet_clean/lib/csrc/uncertainty_pnp/un_pnp_utils.py", line 1, in <module>
    from lib.csrc.uncertainty_pnp._ext import lib, ffi
ImportError: libceres.so.2: cannot open shared object file: No such file or directory

I have followed the readme.md to (I think) successfully have compiled lib/csrc/uncertainty_pnp. 

I have also run: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/clean_pvnet/lib/csrs/uncertainty_pnp/lib 

I have also tried updating the soft links on all libceres.so.* files by:
rm libceres.so
rm libceres.so.2
ln -s libceres.so.2.0.0 libceres.so.2
ln -s libceres.so.2 libceres.so

I am running on python 3.6.10 with OS linux (64-bit)
Any ideas what might be wrong?

**Comment by pengsida** [comment]
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./lib/csrc/uncertainty_pnp/lib`.

**Comment by toblo956** [comment]
I have tried that, I still get the same error.

**Comment by pengsida** [comment]
Could you run `echo $LD_LIBRARY_PATH` and list what is printed.

**Comment by toblo956** [comment]
echo $LD_LIBRARY_PATH
:./lib/csrc/uncertainty_pnp/lib:/usr/local/cuda/cuda/lib64:/data/people/lofgrto/Projects/pvnet_clean/lib/utils/extend_utils/lib:./lib/csrc/uncertainty_pnp/lib:/data/people/lofgrto/Projects/pvnet_clean/lib/csrc/uncertainty_pnp/lib

**Comment by pengsida** [comment]
It is strange.
Did you run the code via the command line?

**Comment by toblo956** [comment]
Yes

**Comment by pengsida** [comment]
Sorry, I do not know the reason.
