### ISSUE TITLE
gcc: error: /usr/local/cuda-9.0/lib64/libcudart.so: No such file or directory

### ISSUE THREAD

**Issue by yimingli1998** [zju3dv/clean-pvnet#83]
Hello,I tried to run
`cd nn `and `python setup.py build_ext --inplace`, but I got the error:
`generating ./_ext.c
(already up-to-date)
the current directory is '/home/liyiming/clean-pvnet/lib/csrc/nn'
running build_ext
building '_ext' extension
gcc -pthread -B /home/liyiming/anaconda3/envs/pvnet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/liyiming/anaconda3/envs/pvnet/include/python3.7m -c _ext.c -o ./_ext.o
gcc -pthread -shared -B /home/liyiming/anaconda3/envs/pvnet/compiler_compat -L/home/liyiming/anaconda3/envs/pvnet/lib -Wl,-rpath=/home/liyiming/anaconda3/envs/pvnet/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_ext.o src/nearest_neighborhood.cu.o /usr/local/cuda-9.0/lib64/libcudart.so -lstdc++ -o ./_ext.cpython-37m-x86_64-linux-gnu.so
gcc: error: /usr/local/cuda-9.0/lib64/libcudart.so: No such file or directory
Traceback (most recent call last):
  File "/home/liyiming/anaconda3/envs/pvnet/lib/python3.7/distutils/unixccompiler.py", line 205, in link
    self.spawn(linker + ld_args)
  File "/home/liyiming/anaconda3/envs/pvnet/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/liyiming/anaconda3/envs/pvnet/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/liyiming/anaconda3/envs/pvnet/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liyiming/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/liyiming/anaconda3/envs/pvnet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/liyiming/anaconda3/envs/pvnet/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/liyiming/anaconda3/envs/pvnet/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/liyiming/anaconda3/envs/pvnet/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/liyiming/anaconda3/envs/pvnet/lib/python3.7/distutils/command/build_ext.py", line 559, in build_extension
    target_lang=language)
  File "/home/liyiming/anaconda3/envs/pvnet/lib/python3.7/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/liyiming/anaconda3/envs/pvnet/lib/python3.7/distutils/unixccompiler.py", line 207, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    ffibuilder.compile(verbose=True)
  File "/home/liyiming/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/api.py", line 727, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/liyiming/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/recompiler.py", line 1536, in recompile
    compiler_verbose, debug)
  File "/home/liyiming/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/liyiming/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'gcc' failed with exit status 1`

How can I fix it?

**Comment by pengsida** [comment]
Make sure that your computer has cuda-9.0.
