### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by zhuyazhi** [zju3dv/clean-pvnet#84]
您好~我在训练的时候遇到了以下的错误：请问是因为内存小了或者需要调小num_workers的问题吗
root@terminal738d5ee8:/opt/data/private/zhuyazhi/clean-pvnet-master# python train_net.py --cfg_file configs/linemod.yaml model mycat cls_type cat
loading annotations into memory...
Done (t=0.16s)
creating index...
index created!
loading annotations into memory...
Done (t=2.49s)
creating index...
index created!
loading annotations into memory...
Done (t=0.10s)
creating index...
index created!
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 511, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "/root/anaconda3/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/root/anaconda3/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/root/anaconda3/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/root/anaconda3/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/root/anaconda3/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 63, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 2582) is killed by signal: Killed. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_net.py", line 57, in <module>
    main()
  File "train_net.py", line 53, in main
    train(cfg, network)
  File "train_net.py", line 28, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/opt/data/private/zhuyazhi/clean-pvnet-master/lib/train/trainers/trainer.py", line 32, in train
    for iteration, batch in enumerate(data_loader):
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 576, in __next__
    idx, batch = self._get_batch()
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 553, in _get_batch
    success, data = self._try_get_batch()
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 519, in _try_get_batch
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 2582) exited unexpectedly

**Comment by pengsida** [comment]
应该是的。可能把batch size减小或把num_workers减小可以解决。

**Comment by zhuyazhi** [comment]
谢谢~我看到configs/linemod.yaml里面可以改batch_size，请问num_workers是在lib/config/config.py里面修改吗
![捕获](https://user-images.githubusercontent.com/48109799/81407565-37fd5200-916e-11ea-895f-5657280d9420.JPG)

**Comment by zhuyazhi** [comment]
谢谢您~我目前改了batch_size，已经不出错了~
